server:
  port: 8082

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:h2:mem:bookingdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 3000



management:
  endpoints:
    web:
      exposure:
        include: health,info
resilience4j:
  circuitbreaker:
    instances:
      usersServiceCb:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000


  retry:
    instances:
      usersServiceRetry:
        max-attempts: 3
        wait-duration: 300

logging:
  level:
    feign: INFO
    org.springframework.cloud.openfeign: INFO
